version: '2.1'
services:
  datadog-iot:
    build: .
    privileged: true
    restart: always
    network_mode: host
    pid: host
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.balena-socket: '1'
